# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelmetDetection(object):
    def setupUi(self, HelmetDetection):
        HelmetDetection.setObjectName("HelmetDetection")
        HelmetDetection.resize(1250, 800)
        self.showPanel = QtWidgets.QLabel(HelmetDetection)
        self.showPanel.setGeometry(QtCore.QRect(0, 0, 1017, 600))
        self.showPanel.setLineWidth(0)
        self.showPanel.setText("")
        self.showPanel.setPixmap(QtGui.QPixmap(".\\src/Camera.png"))
        self.showPanel.setAlignment(QtCore.Qt.AlignCenter)
        self.showPanel.setObjectName("showPanel")
        self.layoutWidget = QtWidgets.QWidget(HelmetDetection)
        self.layoutWidget.setGeometry(QtCore.QRect(1020, 0, 221, 781))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageSelectBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.imageSelectBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.imageSelectBtn.setBaseSize(QtCore.QSize(200, 50))
        self.imageSelectBtn.setObjectName("imageSelectBtn")
        self.verticalLayout.addWidget(self.imageSelectBtn)
        self.imageDetectionBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.imageDetectionBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.imageDetectionBtn.setBaseSize(QtCore.QSize(200, 50))
        self.imageDetectionBtn.setObjectName("imageDetectionBtn")
        self.verticalLayout.addWidget(self.imageDetectionBtn)
        self.videoSelectBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.videoSelectBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.videoSelectBtn.setBaseSize(QtCore.QSize(200, 50))
        self.videoSelectBtn.setObjectName("videoSelectBtn")
        self.verticalLayout.addWidget(self.videoSelectBtn)
        self.videoDetectionBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.videoDetectionBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.videoDetectionBtn.setBaseSize(QtCore.QSize(200, 50))
        self.videoDetectionBtn.setObjectName("videoDetectionBtn")
        self.verticalLayout.addWidget(self.videoDetectionBtn)
        self.cameraBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.cameraBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.cameraBtn.setBaseSize(QtCore.QSize(200, 50))
        self.cameraBtn.setObjectName("cameraBtn")
        self.verticalLayout.addWidget(self.cameraBtn)
        self.realtimeDetectionBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.realtimeDetectionBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.realtimeDetectionBtn.setBaseSize(QtCore.QSize(200, 50))
        self.realtimeDetectionBtn.setObjectName("realtimeDetectionBtn")
        self.verticalLayout.addWidget(self.realtimeDetectionBtn)
        self.modelBtn1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.modelBtn1.setBaseSize(QtCore.QSize(200, 30))
        self.modelBtn1.setObjectName("modelBtn1")
        self.verticalLayout.addWidget(self.modelBtn1)
        self.modelBtn2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.modelBtn2.setBaseSize(QtCore.QSize(200, 30))
        self.modelBtn2.setObjectName("modelBtn2")
        self.verticalLayout.addWidget(self.modelBtn2)
        self.VLine = QtWidgets.QFrame(HelmetDetection)
        self.VLine.setGeometry(QtCore.QRect(0, 600, 1241, 16))
        self.VLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VLine.setLineWidth(3)
        self.VLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.VLine.setObjectName("VLine")
        self.HLine = QtWidgets.QFrame(HelmetDetection)
        self.HLine.setGeometry(QtCore.QRect(1015, -10, 5, 810))
        self.HLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HLine.setLineWidth(10)
        self.HLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.HLine.setObjectName("HLine")
        self.infoPanel = QtWidgets.QTextBrowser(HelmetDetection)
        self.infoPanel.setGeometry(QtCore.QRect(0, 611, 1017, 190))
        self.infoPanel.setObjectName("infoPanel")

        self.retranslateUi(HelmetDetection)
        QtCore.QMetaObject.connectSlotsByName(HelmetDetection)

    def retranslateUi(self, HelmetDetection):
        _translate = QtCore.QCoreApplication.translate
        HelmetDetection.setWindowTitle(_translate("HelmetDetection", "Form"))
        self.imageSelectBtn.setText(_translate("HelmetDetection", "图像选择"))
        self.imageDetectionBtn.setText(_translate("HelmetDetection", "图像检测"))
        self.videoSelectBtn.setText(_translate("HelmetDetection", "视频选择"))
        self.videoDetectionBtn.setText(_translate("HelmetDetection", "视频检测"))
        self.cameraBtn.setText(_translate("HelmetDetection", "实时画面"))
        self.realtimeDetectionBtn.setText(_translate("HelmetDetection", "实时检测"))
        self.modelBtn1.setText(_translate("HelmetDetection", "模型1"))
        self.modelBtn2.setText(_translate("HelmetDetection", "模型2"))
