# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableForm(object):
    def setupUi(self, TableForm):
        TableForm.setObjectName("TableForm")
        TableForm.resize(1117, 766)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TableForm.setWindowIcon(icon)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(TableForm)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(TableForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(TableForm)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{border-top-width:0;\n"
"        border-right-width:0;\n"
"        border-left-width:0;\n"
"        border-bottom-width:2px;\n"
"        border-style:solid;\n"
"}")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.exDataBtn = QtWidgets.QPushButton(TableForm)
        self.exDataBtn.setMinimumSize(QtCore.QSize(30, 62))
        self.exDataBtn.setObjectName("exDataBtn")
        self.horizontalLayout_3.addWidget(self.exDataBtn)
        self.horizontalLayout_3.setStretch(0, 8)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(TableForm)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(TableForm)
        QtCore.QMetaObject.connectSlotsByName(TableForm)

    def retranslateUi(self, TableForm):
        _translate = QtCore.QCoreApplication.translate
        TableForm.setWindowTitle(_translate("TableForm", "数据导出"))
        self.label.setText(_translate("TableForm", "检索:"))
        self.exDataBtn.setText(_translate("TableForm", "导出选中数据"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableForm", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableForm", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TableForm", "时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TableForm", "佩戴安全帽总数"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TableForm", "未佩戴安全帽总数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TableForm", "总人数"))
from src import icons_rc
